const Prompts = [
    {t:'Go towards someone who needs help', p:'went towards someone who needed help'},
    {t:'Walk away from trouble', p:'walked away from troubled'},
    {t:'Move towards the sun', p:'moved towards the sun'},
    {t:'Find somewhere to sit, linger there for a while', p:'found somewhere to sit and lingered'},
    {t:'Find a corner to stand and linger until you\'re done observing', p:'lingered on a corner'},
    {t:'Avert your eyes from those around you', p:'avoided eye contact'},
    {t:'Look people in the eyes as they walk by you', p:'made eye contact with strangers'},
    {t:'Walk away from a place where you\'ve been hurt', p:'walked away from a place they\'ve been hurt'},
    {t:'Walk towards a place where you aspire to be', p:'walked towards a place they aspire to be'},
    {t:'Look out for your favorite color', p:'looked for their favorite color'},
    {t:'Go towards something shiny', p:'went towards something shiny'},
    {t:'Find flowers, real or fake', p:'searched for flowers'},
    {t:'Stretch your arms out, walk in the direction of your longer arm', p:'walked in the direction of their longer arm'},
    {t:'Take a breath, walk towards the better smell', p:'walked towards a nice smell'},
    {t:'Go towards people who are less fortunate than you', p:'went towards people less fortunate than them'},
    {t:'Walk away from authority', p:'walked away from authority'},
    {t:'Walk towards noise, pleasant or unpleasant', p:'followed a noise'},
    {t:'Follow the direction of litter on the sidewalk', p:'followed litter on the sidewalk'},
    {t:'Walk towards a construction site, notice what\'s changing', p:'searched for a construction site'},
    {t:'Look out for a new building near you', p:'searched for new buildings'},
    {t:'Look out for very old buildings, why is it still there?', p:'searched for old buildings'},
    {t:'Head towards a quieter place', p:'went towards a quiet placee'},
    {t:'Walk half as quickly', p:'walked half as quickly'},
    {t:'Walk as if you were gentle', p:'walked as if they were gentle'},
    {t:'Walk as if you were in power', p:'walked as if they were powerful'},
    {t:'Walk like the person you admire most', p:'walked like they person they admire most'},
    {t:'Make up secrets about the people around you', p:'made up secrets of those around them'},
    {t:'Walk in the direction of somewhere you wouldn\'t walk at night', p:'went in a direction they wouldn\'t go at night'},
    {t:'Walk in the direction of where\'d you sleep if you didn\'t have a home', p:'went in the direction of where\'d they sleep if they didn\'t have a home'},
    {t:'Walk as if there was no one else around', p:'walked as if there was no one else around'},
    {t:'Walk as if you have a right to be here', p:'walked as if they had a right to be here'},
    {t:'Look out for beautiful buildings', p:'searched for beautiful builings'},
    {t:'Find buildings that look out of place', p:'found builings that looked out of place'},
    {t:'Find a place that is open to everyone', p:'found a place that\'s open to everyone'},
    {t:'Walk towards a place where you feel good', p:'walked towards a place they feel good'},
    {t:'Look into windows, find colors there', p:'looked into windows'},
    {t:'Find a corner that you find funny', p:'found a funny corner'},
    {t:'Find a sign that makes you laugh', p:'found a funny sign'},
    {t:'Follow the next bus that you see', p:'followed a bus'},
    {t:'Find something rough', p:'searched for something soft'},
    {t:'Find something soft', p:'searched for something soft'},
    {t:'Walk as if you were tough', p:'walked as if they were tough'},
    {t:'Find a spot on the sidewalk to linger on', p:'lingered on a sidewalk'},
    {t:'Walk towards a bright light', p:'walked towards a bright light'},
    {t:'Look up, go towards tall buildings', p:'went towards tall buildings'},
    {t:'Go where your favorite person would go', p:'went towards a place their favorite person would go'},
    {t:'Search for your reflection', p:'searched for their reflection'},
    {t:'Turn towards geometric lines', p:'turned towards geometrics lines'},
    {t:'Go towards closed down buildings', p:'found abandoned buildings'},
    {t:'Walk towards a place you don\'t understand', p:'walked towards a place they don\'t understand'},
    {t:'Head in the direction of a place you know well', p:'went towards a familiar place'},
    {t:'Head towards a colorful street', p:'found a colorful street'},
    {t:'Go where you would have gone when you were 13', p:'went towards where their 13 year old self would have gone'},
    {t:'Turn to a crowded area', p:'searched for a crowded area'},
    {t:'Search for repeating patterns', p:'found repeating patterns'},
    {t:'Search for a public building you can walk in to', p:'found a public building and walked into it'},
    {t:'Find a place to watch people come and go', p:'found a place where people come and go'},
    {t:'Find a place to watch people laugh', p:'found a place where peopel laugh'},
    {t:'Find a place to be close enough to listen to people', p:'found a place to listen to people'},
    {t:'Turn towards a curvy street', p:'searched for a curvy street'},
    {t:'Search for gated buildings', p:'searched for gated buildings'},
    {t:'Search for the tallest tree', p:'found the tallest treet'},
    {t:'Search for a sign for something no longer exists', p:'searched a sign of something that no longer exists'}
];

export { Prompts }